LIBNAME clinical '/home/u64498565/cdm project/raw dataset';
run;

PROC IMPORT DATAFILE='/home/u64498565/cdm project/raw dataset/DEMOG.csv'
           OUT=clinical.demog
           DBMS=csv
           replace;
           getnames=yes;
run;

PROC CONTENTS DATA= Clinical.demog;                                                                                                                                                                                          
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= Clinical.demog;                                                                                                                                                                                             
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
         /*(first edit check)*/                                                                                                                                                                                            
                                                                                                                                                                                                                           
DATA missing_age;                                                                                                                                                                                                          
               set Clinical.demog;                                                                                                                                                                                           
               if missing(age);                                                                                                                                                                                            
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.missing_age;                                                                                                                                                                                         
   title "Edit check - Missing age";                                                                                                                                                                                       
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
       /*(second edit check on invalid age)*/                                                                                                                                                                              
DATA invalid_age;                                                                                                                                                                                                          
             set Clinical.demog;                                                                                                                                                                                             
             if not missing(age) and (age <18 or age >80);                                                                                                                                                                 
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.invalid_age;                                                                                                                                                                                         
   title " Edit check - invalid age";                                                                                                                                                                                      
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
      /*(validate sex)*/                                                                                                                                                                                                   
                                                                                                                                                                                                                           
DATA invalid_sex;                                                                                                                                                                                                          
                set clinical.demog;                                                                                                                                                                                          
                if sex not in ('M', 'F');                                                                                                                                                                                  
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
proc print data= work.invalid_sex;                                                                                                                                                                                         
title " Edit check - invalid SEX";                                                                                                                                                                                         
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
      /*(validate treatment grp- missing or invalid )*/                                                                                                                                                                    
DATA invalid_treatment;                                                                                                                                                                                                    
                set Clinical.demog;                                                                                                                                                                                          
                if missing(trtgrp)                                                                                                                                                                                         
                or trtgrp not in ("Drug A", "Placebo");                                                                                                                                                                    
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= WORK.invalid_treatment;                                                                                                                                                                                   
 title " Edit check - invalid or misssing treatment";                                                                                                                                                                      
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
             /*( find duplicate subject id)*/                                                                                                                                                                              
PROC SORT DATA=clinical.demog                                                                                                                                                                                                
              out=demog_sorted                                                                                                                                                                                             
              NODUPKEY                                                                                                                                                                                                     
              dupout= duplicate_subjectid;                                                                                                                                                                                 
       by subjid;                                                                                                                                                                                                          
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.duplicate_subjectid ;                                                                                                                                                                                
title "Edit check - duplicate subject Id";                                                                                                                                                                                 
run;
PROC CONTENTS DATA= Clinical.demog;                                                                                                                                                                                          
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= Clinical.demog;                                                                                                                                                                                             
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
         /*(first edit check)*/                                                                                                                                                                                            
                                                                                                                                                                                                                           
DATA missing_age;                                                                                                                                                                                                          
               set Clinical.demog;                                                                                                                                                                                           
               if missing(age);                                                                                                                                                                                            
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.missing_age;                                                                                                                                                                                         
   title "Edit check - Missing age";                                                                                                                                                                                       
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
       /*(second edit check on invalid age)*/                                                                                                                                                                              
DATA invalid_age;                                                                                                                                                                                                          
             set Clinical.demog;                                                                                                                                                                                             
             if not missing(age) and (age <18 or age >80);                                                                                                                                                                 
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.invalid_age;                                                                                                                                                                                         
   title " Edit check - invalid age";                                                                                                                                                                                      
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
      /*(validate sex)*/                                                                                                                                                                                                   
                                                                                                                                                                                                                           
DATA invalid_sex;                                                                                                                                                                                                          
                set Clinical.demog;                                                                                                                                                                                          
                if sex not in ('M', 'F');                                                                                                                                                                                  
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
proc print data= work.invalid_sex;                                                                                                                                                                                         
title " Edit check - invalid SEX";                                                                                                                                                                                         
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
      /*(validate treatment grp- missing or invalid )*/                                                                                                                                                                    
DATA invalid_treatment;                                                                                                                                                                                                    
                set Clinical.demog;                                                                                                                                                                                          
                if missing(trtgrp)                                                                                                                                                                                         
                or trtgrp not in ("Drug A", "Placebo");                                                                                                                                                                    
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= WORK.invalid_treatment;                                                                                                                                                                                   
 title " Edit check - invalid or misssing treatment";                                                                                                                                                                      
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
             /*( find duplicate subject id)*/                                                                                                                                                                              
PROC SORT DATA=clinical.demog                                                                                                                                                                                                
              out=demog_sorted                                                                                                                                                                                             
              NODUPKEY                                                                                                                                                                                                     
              dupout= duplicate_subjectid;                                                                                                                                                                                 
       by subjid;                                                                                                                                                                                                          
run;                                                                                                                                                                                                                       
                                                                                                                                                                                                                           
PROC PRINT DATA= work.duplicate_subjectid ;                                                                                                                                                                                
title "Edit check - duplicate subject Id";                                                                                                                                                                                 
run;
